### PR TITLE
Added olcf repo for rhea openmpi

### PR DESCRIPTION
**Pull request by suchyta1**
This relates to #48. It'll still need a `spack repo add` like with the `wdmapp` namespace. Adding the patch files probably isn't really necessary, as it's not actually being built. But I just copied the full `openmpi` directory.

### CODE REVIEW

**Comment by suchyta1** [comment]
> Thanks, that seems like a better solution than rebuilding openmpi.
> 
> Since the `olcf` repo is specific to rhea (or do you anticipate needing it elsewhere?), I think it may be preferable to mv it into `rhea/spack`, what do you think?
> 
> When I first added the rhea support, I didn't update the docs to add corresponding instructions. Do you happen to want to do that? ;)

Yes, I can move it into Rhea. In principle, it's like this on Summit too, but I think it only shows up when I use PGI, which won't install some of the things GCC can install from source. (But spectrum-mpi isn't in an `olcf` repo.) But at any rate, it's probably better to keep them in scoped subdirectories anyway.

And sure, I'll take a look at the documentation.

**Comment by suchyta1** [comment]
I updated, but I don't really know how to rebuild the documentation.

**Comment by germasch** [comment]
Thanks! One more thing (sorry for being a pain): Can you move `rhea/olcf` to `rhea/spack/olcf`?

**Comment by suchyta1** [comment]
> Thanks! One more thing (sorry for being a pain): Can you move `rhea/olcf` to `rhea/spack/olcf`?

No problem

**Comment by germasch** [comment]
Thanks!

**Pull request merged**
