### PR TITLE
libfabric@1.6.1 on Rhea

### PR DESCRIPTION
**Pull request by suchyta1**
- Tau variant `-papi` is because of #51 
- Newer version of `libfabric` and RDMA don't work properly (yet) on Rhea.

### CODE REVIEW

**Comment by germasch** [comment]
This looks fine to me, but let's see whether @kuck can chime in.

**Comment by suchyta1** [comment]
Perhaps I need to `module load papi`. I didn't think to do that, but I can easily try.

**Comment by germasch** [comment]
> This looks fine to me, but let's see whether @kuck can chime in.

I meant @khuck, of course...

**Comment by suchyta1** [comment]
I did the the `module load` and the didn't change anything.

**Comment by suchyta1** [comment]
@germasch I've kept PAPI now, so I'll squash and merge.

**Pull request merged**
