### PR TITLE
install coupler that supports successfull xgc-gene coupled cyclone runs

### PR DESCRIPTION
**Pull request by cwsmith**
The following script/commands will install wdmapp for running the cyclone problem with xgc-coupler-gene on summit.

```shell
#!/bin/bash -x
externalCpl=$1
[[ "$externalCpl" != "on" &&
  "$externalCpl" != "off"  ]] &&
  echo "Usage: $0 <externalCpl=on|off>" &&
  exit 1;

date=`date +%F-%H-%M`
wdmDir=$SCRATCH/wdmExtCpl_${date}
mkdir -p $wdmDir
cd $wdmDir
git clone -b v0.15.4 https://github.com/spack/spack.git
git clone -b extCplv0154 git@github.com:SCOREC/wdmapp-config.git
cd spack
export SPACK_ROOT=$PWD
source $SPACK_ROOT/share/spack/setup-env.sh
which spack # sanity check

#yaml files
mkdir $SPACK_ROOT/etc/spack/linux
cp $wdmDir/wdmapp-config/summit/spack/*.yaml $_
cd $_
mv packages.yaml packages.minimal.yaml
ln -s packages-extended.yaml packages.yaml

#add the wdmapp repo
spack repo add --scope site $wdmDir/wdmapp-config/spack/wdmapp
spack repo list # sanity check

# setup scratch space for spack
spackScratch=/gpfs/alpine/phy122/scratch/$USER/spack-stage-${date}
mkdir -p $spackScratch
(
cat <<APPEND_HEREDOC
config:
  build_stage:
   - \$tempdir/\$user/spack-stage
   - $spackScratch
   - ~/.spack/stage
APPEND_HEREDOC
) >> $SPACK_ROOT/etc/spack/config.yaml

spec="wdmapp +externalCpl"
[ $externalCpl == "off" ] && spec="wdmapp"
spack spec -I $spec
spack install $spec
```

### CODE REVIEW

**Review by germasch — APPROVED** [review]
LGTM (I had tested it with the previous tag, installed nicely except for tau, which is an unrelated issue).

**Comment by cwsmith** [comment]
Thank you for testing.  I pushed the new tag and corresponding package changes, that installed without issue, and am now testing the install script without the coupler (just updated to take a cmd line arg).

**Comment by cwsmith** [comment]
@germasch I'm thinking that when the `externalCpl` variant off the coupler should not be installed.  Does that make sense to you?  Specifically, I propose we remove the following lines from the wdmapp meta package:

https://github.com/wdmapp/wdmapp-config/blob/d6cf07e0f4c6df47d73c4542fc955cad0edd6750/spack/wdmapp/packages/wdmapp/package.py#L37-L38

With this change `spack spec -I wdmapp` concretizes successfully.  I'm testing the install now.

**Comment by germasch** [comment]
Yes, I agree they should be removed.

**Pull request merged**
